; PlatformIO Project Configuration File
; Rover-C Test Project for M5StickC Plus V1.1

[env:m5stick-c]
platform = espressif32@4.2.0
board = m5stick-c
framework = arduino
lib_deps = 
    m5stack/M5Unified@^0.2.17
monitor_speed = 115200
upload_speed = 1500000